import json
import os

MAX_FILES_PER_QUESTION = 5

SYSTEM_PROMPT = """You are a codebase assistant. You have been given a structured summary of a software project generated by a static analysis engine.
Your job is to answer the user's questions about the codebase clearly and concisely.
Base your answers on the context provided. If you are unsure, say so — do not make things up.
Keep answers focused and practical. The user may be a beginner or an experienced developer."""

FILE_SELECTOR_PROMPT = """You are a file selector for a codebase assistant.
Given a list of file paths and a user question, return a JSON array of the most relevant file paths needed to answer the question.
Select up to {max_files} files. Only select files that are genuinely needed.
Return ONLY a JSON array of file paths, no explanation. Example: ["./src/main.py", "./src/routes.py"]"""


def start_deep_dive(context: str, provider: str, api_key: str, ranked_files: list):
    """
    Starts an interactive RAG conversation loop about the codebase.
    For each question: selects relevant files -> loads full content -> sends to LLM.
    """
    print("\n=== Deep Dive Mode ===")
    print("Ask anything about your codebase. Type 'exit' to quit.\n")

    conversation_history = []

    # Prime the conversation with our context summary
    initial_message = f"Here is a structured summary of the codebase I want to ask about:\n\n{context}"
    conversation_history.append({"role": "user", "content": initial_message})

    ack = _send_message(conversation_history, provider, api_key)
    if ack is None:
        print("[Error] Could not connect to LLM. Exiting Deep Dive.")
        return
    conversation_history.append({"role": "assistant", "content": ack})

    file_paths = [fp for fp, _ in ranked_files]

    # Main conversation loop
    while True:
        try:
            user_input = input("You: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting Deep Dive.")
            break

        if not user_input:
            continue
        if user_input.lower() in ('exit', 'quit', 'q'):
            print("Exiting Deep Dive.")
            break

        # --- RAG STEP 1: select relevant files for this question ---
        relevant_files = _select_relevant_files(user_input, file_paths, provider, api_key)

        # --- RAG STEP 2: load full content of selected files ---
        file_content = _load_full_files(relevant_files)

        # --- RAG STEP 3: build enriched message with full file content ---
        enriched_message = user_input
        if file_content:
            enriched_message = (
                f"{user_input}\n\n"
                f"Here are the full contents of the relevant files:\n\n{file_content}"
            )

        conversation_history.append({"role": "user", "content": enriched_message})

        response = _send_message(conversation_history, provider, api_key)
        if response is None:
            print("[Warning] LLM call failed. Try again.")
            conversation_history.pop()
            continue

        conversation_history.append({"role": "assistant", "content": response})
        print(f"\nAssistant: {response}\n")


def _select_relevant_files(question: str, file_paths: list, provider: str, api_key: str) -> list:
    """Ask LLM which files are relevant to the user's question. Falls back to top 3 files on failure."""
    prompt = (
        FILE_SELECTOR_PROMPT.format(max_files=MAX_FILES_PER_QUESTION) +
        f"\n\nAvailable files:\n" + "\n".join(file_paths) +
        f"\n\nUser question: {question}"
    )
    history = [{"role": "user", "content": prompt}]

    try:
        response = _send_message(history, provider, api_key)
        if response is None:
            return file_paths[:3]
        clean = response.strip().replace('```json', '').replace('```', '').strip()
        selected = json.loads(clean)
        # validate returned paths actually exist in our list
        valid = [fp for fp in selected if fp in file_paths]
        return valid[:MAX_FILES_PER_QUESTION] if valid else file_paths[:3]
    except Exception:
        return file_paths[:3]  # fallback to top 3 ranked files


def _load_full_files(file_paths: list) -> str:
    """Read full content of selected files and format as a string block."""
    blocks = []
    for fp in file_paths:
        try:
            with open(fp, encoding='utf-8') as f:
                content = f.read()
            blocks.append(f"--- {fp} ---\n{content}")
        except (OSError, UnicodeDecodeError):
            blocks.append(f"--- {fp} ---\n[Could not read file]")
    return "\n\n".join(blocks)


def _send_message(history: list, provider: str, api_key: str) -> str | None:
    """Send full conversation history to LLM, return response text or None on failure."""
    try:
        if provider == 'gemini':
            return _gemini_chat(history, api_key)
        elif provider == 'openai':
            return _openai_chat(history, api_key)
        elif provider == 'anthropic':
            return _anthropic_chat(history, api_key)
        else:
            print(f"[Warning] Unsupported provider: {provider}")
            return None
    except Exception as e:
        print(f"[Warning] LLM error: {e}")
        return None


def _gemini_chat(history: list, api_key: str) -> str:
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key)

    contents = []
    for msg in history:
        role = "user" if msg["role"] == "user" else "model"
        contents.append(types.Content(role=role, parts=[types.Part(text=msg["content"])]))

    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=contents,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT
        )
    )
    return response.text


def _openai_chat(history: list, api_key: str) -> str:
    from openai import OpenAI
    client = OpenAI(api_key=api_key)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}] + history
    response = client.chat.completions.create(
        model='gpt-4o-mini',
        messages=messages
    )
    return response.choices[0].message.content


def _anthropic_chat(history: list, api_key: str) -> str:
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model='claude-3-haiku-20240307',
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=history
    )
    return response.content[0].text