import os
import fnmatch
from context_pack.language_detector import EXTENSION_MAP

MAX_FILES = 5000

# folders to always ignore — entire subtree skipped
IGNORE_FOLDERS = {
    'venv', '__pycache__', '.git', 'node_modules', '.idea', '.vscode',
    'dist', 'build', 'target', 'runtime', 'vendor', 'examples', 'example',
    'docs', 'doc', 'assets', 'asset', 'static', 'migrations', 'migration',
    'fixtures', 'fixture', 'third_party', 'contrib', 'tools', 'tool',
    'ci', '.github', 'cmake', 'bin', 'obj', 'out', 'coverage',
    'gen', 'generated', 'autoconf', 'autom4te.cache', 'compiled', 'bundle',
    'bundles', '.next', '__sapper__', 'scripts', 'script',
    'test', 'tests', 'spec', 'specs', '__tests__', '__mocks__', '__fixtures__',
    '__snapshots__', 'e2e', 'integration', 'unit', 'benchmark', 'benchmarks',
    'storybook', '.storybook', 'stories', 'story',
    'evals', 'eval', 'bench', 'playground', 'demo', 'demos', 'sample', 'samples',
    'benchmark-apps', 'testing', 'codemod', 'transforms', 'codemods',
    'crates', 'templates', 'template', 'proto', 'protos', 'schema', 'schemas',
    'types', 'typings', 'type-stubs', 'stubs'
}

# file extensions to always skip even if in EXTENSION_MAP
SKIP_EXTENSIONS = {'.d.ts'}

# file patterns to always skip
SKIP_PATTERNS = {'*.min.js', '*.min.ts', '*.min.css'}

# output files generated by context-pack itself
IGNORE_FILES = {'context.md', 'context.txt'}


def _should_skip_file(filename: str) -> bool:
    """Check if a file should be skipped based on extension or pattern."""
    if filename in IGNORE_FILES:
        return True
    # check compound extensions like .d.ts
    for skip_ext in SKIP_EXTENSIONS:
        if filename.endswith(skip_ext):
            return True
    # check patterns like *.min.js
    for pattern in SKIP_PATTERNS:
        if fnmatch.fnmatch(filename, pattern):
            return True
    return False


def _pass1_collect_approved_folders(path: str, ignore_folders: set) -> set:
    """
    Pass 1: Walk full tree, collect folder names and file counts only.
    No file reads — just metadata.
    Returns set of approved folder paths to scan in Pass 2.
    """
    approved_folders = set()

    for root, dirs, files in os.walk(path):
        # prune ignored folders in-place so os.walk skips their subtrees
        dirs[:] = [d for d in dirs if d not in ignore_folders]

        # count non-useless files in this folder
        valid_file_count = sum(
            1 for f in files
            if not _should_skip_file(f) and
            any(f.endswith(ext) for ext in EXTENSION_MAP.keys())
        )

        if valid_file_count > 0:
            approved_folders.add(root)

    return approved_folders


def scan_directory(path="."):
    """Walk directory using two-pass approach to find code files efficiently."""

    # validate path
    if not os.path.exists(path):
        raise ValueError(f"Path does not exist: {path}")
    if not os.path.isdir(path):
        raise ValueError(f"Path is not a directory: {path}")

    # merge hardcoded ignore list with .contextignore
    ignore_folders = set(IGNORE_FOLDERS)
    ignore_patterns = set()

    contextignore_path = os.path.join(path, '.contextignore')
    if os.path.exists(contextignore_path):
        try:
            with open(contextignore_path, encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    if '*' in line or '?' in line:
                        ignore_patterns.add(line)
                    else:
                        ignore_folders.add(line.strip('/'))
            print(f"[info] Loaded .contextignore from {contextignore_path}")
        except (OSError, UnicodeDecodeError):
            pass

    dependency_files = [
        'requirements.txt', 'Pipfile', 'pyproject.toml',
        'package.json', 'go.mod', 'Cargo.toml',
        'pom.xml', 'build.gradle', 'composer.json',
        'pubspec.yaml', 'mix.exs', 'Package.swift',
    ]

    code_extensions = set(EXTENSION_MAP.keys())

    # --- PASS 1: collect approved folders (no file reads) ---
    approved_folders = _pass1_collect_approved_folders(path, ignore_folders)

    # --- PASS 2: collect actual files from approved folders only ---
    code_files = []
    warned = False

    for folder in approved_folders:
        try:
            for filename in os.listdir(folder):
                filepath = os.path.join(folder, filename)
                if not os.path.isfile(filepath):
                    continue
                if _should_skip_file(filename):
                    continue
                if any(filename.endswith(ext) for ext in code_extensions):
                    # check user-defined patterns from .contextignore
                    if any(fnmatch.fnmatch(filename, p) for p in ignore_patterns):
                        continue
                    code_files.append(filepath)
                    if len(code_files) >= MAX_FILES and not warned:
                        print(f"[warning] Large codebase detected — limiting to {MAX_FILES} files for performance.")
                        warned = True
                    if len(code_files) >= MAX_FILES:
                        break
        except (OSError, PermissionError):
            continue
        if len(code_files) >= MAX_FILES:
            break

    # check for dependency files in root and one level deep
    found_dependency_files = []
    search_dirs = [path] + [
        os.path.join(path, d) for d in os.listdir(path)
        if os.path.isdir(os.path.join(path, d))
    ]
    for search_dir in search_dirs:
        for dep_file in dependency_files:
            full_path = os.path.join(search_dir, dep_file)
            if os.path.exists(full_path) and full_path not in found_dependency_files:
                found_dependency_files.append(full_path)

    return code_files, found_dependency_files


if __name__ == "__main__":
    files, deps = scan_directory(".")
    print(f"Found {len(files)} code files:")
    for f in files[:20]:
        print(f"  - {f}")
    print(f"\nFound {len(deps)} dependency files:")
    for d in deps:
        print(f"  - {d}")